--------------------------------------------------------------------------------
-- VHDL wrapper around the Gowin IP-Core-Generator "DP" (true dual port BSRAM)
-- primitive, exposing the same port interface as the behavioural `dpram`
-- entity in dpram.vhd, so it can replace individual instantiations without
-- touching the rest of the surrounding architecture.
--
-- Unlike the behavioural dpram, this wrapper does not synthesise -- it
-- instantiates the exact Verilog module generated by Gowin's IP Core
-- Generator (Hard Module > Memory > Block Memory > DP), configured with
-- WRITE_MODE0 = WRITE_MODE1 = "Normal" (2'b00) on both ports, matching the
-- configuration nand2mario/snestang uses for its OAM/line-buffer memories
-- (see Gowin_DPB_OAM.v).  That write mode is guaranteed placeable by the
-- Place & Route tool, sidestepping the WRITE_MODE1 = 2'b10 (PA2122) failure
-- that behavioural (inferred) write-first RAM can trigger on some instances.
--
-- One VHDL entity per (addr_width, data_width) pair is needed, because the
-- underlying Gowin_DP module is generated with fixed port widths (it is not
-- itself generic).  This file provides the wrapper for the (8, 16)
-- configuration used by HUC6270's SAT (sprite attribute table).  Copy this
-- pattern -- new entity name, new component reference, same body shape -- for
-- any other fixed size that needs the same treatment (e.g. SPR_LINE_BUF0/1
-- at (9, 10), generated separately as e.g. Gowin_DP_1).
--
-- Behaviour note: with WRITE_MODE = Normal, a port does NOT see its own
-- freshly-written data forwarded to its output in the same cycle (no
-- write-first/bypass), unlike port A of the original dpram entity. Every
-- current user of dpram's port B (SAT, SPR_LINE_BUF0/1, RAM work memory,
-- VRAM0) only ever writes and reads at disjoint times (clear sweep vs.
-- normal access), so this is not expected to change behaviour -- but it is
-- the one semantic difference to keep in mind if this wrapper is reused
-- elsewhere.
--------------------------------------------------------------------------------

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity dpram_ip_8x16 is
	generic (
		disable_value : std_logic := '1'
	);
	PORT
	(
		clock			: in  STD_LOGIC;
		address_a	: in  STD_LOGIC_VECTOR (7 DOWNTO 0);
		data_a		: in  STD_LOGIC_VECTOR (15 DOWNTO 0) := (others => '0');
		enable_a		: in  STD_LOGIC := '1';
		wren_a		: in  STD_LOGIC := '0';
		q_a			: out STD_LOGIC_VECTOR (15 DOWNTO 0);
		cs_a        : in  std_logic := '1';

		address_b	: in  STD_LOGIC_VECTOR (7 DOWNTO 0) := (others => '0');
		data_b		: in  STD_LOGIC_VECTOR (15 DOWNTO 0) := (others => '0');
		enable_b		: in  STD_LOGIC := '1';
		wren_b		: in  STD_LOGIC := '0';
		q_b			: out STD_LOGIC_VECTOR (15 DOWNTO 0);
		cs_b        : in  std_logic := '1'
	);
end entity;

architecture STRUCT of dpram_ip_8x16 is

	component Gowin_DP is
		port (
			douta : out std_logic_vector(15 downto 0);
			doutb : out std_logic_vector(15 downto 0);
			clka  : in  std_logic;
			ocea  : in  std_logic;
			cea   : in  std_logic;
			reseta: in  std_logic;
			wrea  : in  std_logic;
			clkb  : in  std_logic;
			oceb  : in  std_logic;
			ceb   : in  std_logic;
			resetb: in  std_logic;
			wreb  : in  std_logic;
			ada   : in  std_logic_vector(7 downto 0);
			dina  : in  std_logic_vector(15 downto 0);
			adb   : in  std_logic_vector(7 downto 0);
			dinb  : in  std_logic_vector(15 downto 0)
		);
	end component;

	signal douta_i, doutb_i : std_logic_vector(15 downto 0);

begin

	q_a <= douta_i when cs_a = '1' else (others => disable_value);
	q_b <= doutb_i when cs_b = '1' else (others => disable_value);

	u_dp : Gowin_DP
	port map (
		douta  => douta_i,
		doutb  => doutb_i,
		clka   => clock,
		ocea   => enable_a,
		cea    => enable_a and cs_a,
		reseta => '0',
		wrea   => wren_a and cs_a,
		clkb   => clock,
		oceb   => enable_b,
		ceb    => enable_b and cs_b,
		resetb => '0',
		wreb   => wren_b and cs_b,
		ada    => address_a,
		dina   => data_a,
		adb    => address_b,
		dinb   => data_b
	);

end architecture;
