#!/usr/bin/env python3
"""Generate rtl/mem_init_pkg.vhd from the Altera .mif memory initialisation files.

GowinSynthesis does not support the Altera `init_file` attribute (nor VHDL
file I/O at elaboration time), so the two initialised memories of the core are
converted into plain VHDL constant tables.  Re-run this script whenever one of
the .mif sources changes:

    python tools/mif2vhd.py

Only the two files that the TurboGrafx-16 core actually initialises are
handled:

  rtl/HUC6280/voltab_small.mif      256 x 12  PSG attenuation table
  rtl/huc6260_palette_init.mif      512 x  9  VCE power-on palette
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SOURCES = [
    ("VOLTAB_INIT", os.path.join(ROOT, "rtl", "HUC6280", "voltab_small.mif"), 256, 12),
    ("PALETTE_INIT", os.path.join(ROOT, "rtl", "huc6260_palette_init.mif"), 512, 9),
]

OUT = os.path.join(ROOT, "rtl", "mem_init_pkg.vhd")

ENTRY_RE = re.compile(r"^\s*([0-9a-fA-F]+)\s*:\s*([0-9a-fA-F]+)\s*;", re.M)


def read_mif(path, depth):
    with open(path, "r") as handle:
        text = handle.read()
    body = text.split("BEGIN", 1)[1] if "BEGIN" in text else text
    values = [0] * depth
    seen = 0
    for addr, data in ENTRY_RE.findall(body):
        index = int(addr, 16)
        if index >= depth:
            raise ValueError("%s: address %X out of range" % (path, index))
        values[index] = int(data, 16)
        seen += 1
    if seen != depth:
        raise ValueError("%s: expected %d entries, found %d" % (path, depth, seen))
    return values


def emit_table(name, values, width):
    lines = []
    lines.append("  constant %s : mem_init_t(0 to %d) := (" % (name, len(values) - 1))
    for i, value in enumerate(values):
        bits = format(value & ((1 << width) - 1), "0%db" % width).rjust(16, "0")
        sep = "," if i != len(values) - 1 else ""
        lines.append('    %d => "%s"%s' % (i, bits, sep))
    lines.append("  );")
    return lines


def main():
    out = []
    out.append("-- Automatically generated by tools/mif2vhd.py - do not edit by hand.")
    out.append("--")
    out.append("-- Memory initialisation tables converted from the upstream Altera .mif")
    out.append("-- files so that the design can be synthesised with GowinSynthesis, which")
    out.append("-- has no equivalent of altsyncram's init_file attribute.")
    out.append("--")
    for _, path, _, _ in SOURCES:
        out.append("--   source: %s" % os.path.relpath(path, ROOT).replace("\\", "/"))
    out.append("")
    out.append("library IEEE;")
    out.append("use IEEE.STD_LOGIC_1164.all;")
    out.append("")
    out.append("package mem_init_pkg is")
    out.append("")
    out.append("  type mem_init_t is array (natural range <>) of std_logic_vector(15 downto 0);")
    out.append("")
    for name, path, depth, width in SOURCES:
        values = read_mif(path, depth)
        out.extend(emit_table(name, values, width))
        out.append("")
    out.append("end package mem_init_pkg;")
    out.append("")

    with open(OUT, "w") as handle:
        handle.write("\n".join(out))
    print("wrote %s" % OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
